version: '{build}'

build:
  verbosity: detailed
  
clone_folder: c:\projects\gluon-plasma

image: Visual Studio 2019

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init

before_build:
  # Setup MSVC Environment
  - call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  # CMake
  - cmake -G Ninja
    "-DCMAKE_BUILD_TYPE=Release"
    %APPVEYOR_BUILD_FOLDER%
  # Build
  - ninja
