version: '{build}'

clone_script:
- cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
- cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

build:
  verbosity: detailed
  
clone_folder: c:\projects\gluon-plasma

image: Visual Studio 2019
